// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsOE1mAB-Xqpe5Kb1simwYYMlOFrw_nvw',
    appId: '1:243193667829:web:cfc7f9eab416bdf62ee5bc',
    messagingSenderId: '243193667829',
    projectId: 'gu4rdi4n3y3',
    authDomain: 'gu4rdi4n3y3.firebaseapp.com',
    databaseURL: 'https://gu4rdi4n3y3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gu4rdi4n3y3.firebasestorage.app',
    measurementId: 'G-2J2KTKLMS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJjf4THJKmhWPOgjnFsVblG92QRzSQPvE',
    appId: '1:243193667829:android:1e4cef6e741e399c2ee5bc',
    messagingSenderId: '243193667829',
    projectId: 'gu4rdi4n3y3',
    databaseURL: 'https://gu4rdi4n3y3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gu4rdi4n3y3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIlnzTACNigWyC_UvXaJb7Rhwyd0CMcc',
    appId: '1:243193667829:ios:1c0ef3bb80a0fe702ee5bc',
    messagingSenderId: '243193667829',
    projectId: 'gu4rdi4n3y3',
    databaseURL: 'https://gu4rdi4n3y3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gu4rdi4n3y3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGIlnzTACNigWyC_UvXaJb7Rhwyd0CMcc',
    appId: '1:243193667829:ios:1c0ef3bb80a0fe702ee5bc',
    messagingSenderId: '243193667829',
    projectId: 'gu4rdi4n3y3',
    databaseURL: 'https://gu4rdi4n3y3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gu4rdi4n3y3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsOE1mAB-Xqpe5Kb1simwYYMlOFrw_nvw',
    appId: '1:243193667829:web:64f14f62e4f3470d2ee5bc',
    messagingSenderId: '243193667829',
    projectId: 'gu4rdi4n3y3',
    authDomain: 'gu4rdi4n3y3.firebaseapp.com',
    databaseURL: 'https://gu4rdi4n3y3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gu4rdi4n3y3.firebasestorage.app',
    measurementId: 'G-8W8N3NNXCM',
  );

}